// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: envelope.proto

// Каноническая wire-схема конверта личного сообщения (crypto-protocol.md §3).
// ЭТО КОНТРАКТ: номера полей неизменны; удалённые — в reserved; новые добавляются
// только с новыми номерами (обратная совместимость). Реализацию можно переписывать
// свободно — совместимость держится на этих байтах, а не на коде.
//
// Envelope — то, что клиент сериализует и шлёт POST /messages. Сервер раскладывает:
//   meta/encrypted_payload/escrow/sender_ephemeral_pub/ratchet_envelope/signature → personal_messages
//   wrapped_keys[] → personal_message_keys (по строке на устройство/ВП).

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ContentKind int32

const (
	ContentKind_CK_UNSPECIFIED ContentKind = 0
	ContentKind_CK_TEXT        ContentKind = 1
	ContentKind_CK_VOICE       ContentKind = 2
	ContentKind_CK_IMAGE       ContentKind = 3
	ContentKind_CK_VIDEO       ContentKind = 4
	ContentKind_CK_FILE        ContentKind = 5
	ContentKind_CK_SYSTEM      ContentKind = 6
)

// Enum value maps for ContentKind.
var (
	ContentKind_name = map[int32]string{
		0: "CK_UNSPECIFIED",
		1: "CK_TEXT",
		2: "CK_VOICE",
		3: "CK_IMAGE",
		4: "CK_VIDEO",
		5: "CK_FILE",
		6: "CK_SYSTEM",
	}
	ContentKind_value = map[string]int32{
		"CK_UNSPECIFIED": 0,
		"CK_TEXT":        1,
		"CK_VOICE":       2,
		"CK_IMAGE":       3,
		"CK_VIDEO":       4,
		"CK_FILE":        5,
		"CK_SYSTEM":      6,
	}
)

func (x ContentKind) Enum() *ContentKind {
	p := new(ContentKind)
	*p = x
	return p
}

func (x ContentKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ContentKind) Descriptor() protoreflect.EnumDescriptor {
	return file_envelope_proto_enumTypes[0].Descriptor()
}

func (ContentKind) Type() protoreflect.EnumType {
	return &file_envelope_proto_enumTypes[0]
}

func (x ContentKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ContentKind.Descriptor instead.
func (ContentKind) EnumDescriptor() ([]byte, []int) {
	return file_envelope_proto_rawDescGZIP(), []int{0}
}

type Envelope struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	FormatVersion      uint32                 `protobuf:"varint,1,opt,name=format_version,json=formatVersion,proto3" json:"format_version,omitempty"`                 // = 1; bump только при несовместимой смене раскладки
	Meta               *Metadata              `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`                                                         // plaintext (сервер видит; escrow-политика в §10)
	EncryptedPayload   []byte                 `protobuf:"bytes,3,opt,name=encrypted_payload,json=encryptedPayload,proto3" json:"encrypted_payload,omitempty"`         // Kodium.encryptSymmetric(message_key, zstd(MessageBody)) → nonce||box
	Escrow             *EscrowBlob            `protobuf:"bytes,4,opt,name=escrow,proto3" json:"escrow,omitempty"`                                                     // всегда (ADR-0004)
	SenderEphemeralPub []byte                 `protobuf:"bytes,5,opt,name=sender_ephemeral_pub,json=senderEphemeralPub,proto3" json:"sender_ephemeral_pub,omitempty"` // X25519 pub эфемерной пары отправителя (32 B) — получателю для unwrap
	RatchetEnvelope    []byte                 `protobuf:"bytes,6,opt,name=ratchet_envelope,json=ratchetEnvelope,proto3" json:"ratchet_envelope,omitempty"`            // opaque Kodium RatchetMessage; пусто, если сессии нет (путь A)
	Signature          []byte                 `protobuf:"bytes,7,opt,name=signature,proto3" json:"signature,omitempty"`                                               // Ed25519 detached над canonical_bytes (см. proto/README.md)
	WrappedKeys        []*WrappedKey          `protobuf:"bytes,8,rep,name=wrapped_keys,json=wrappedKeys,proto3" json:"wrapped_keys,omitempty"`                        // по одному на устройство получателя И отправителя (план Б)
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_envelope_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_envelope_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_envelope_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetFormatVersion() uint32 {
	if x != nil {
		return x.FormatVersion
	}
	return 0
}

func (x *Envelope) GetMeta() *Metadata {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *Envelope) GetEncryptedPayload() []byte {
	if x != nil {
		return x.EncryptedPayload
	}
	return nil
}

func (x *Envelope) GetEscrow() *EscrowBlob {
	if x != nil {
		return x.Escrow
	}
	return nil
}

func (x *Envelope) GetSenderEphemeralPub() []byte {
	if x != nil {
		return x.SenderEphemeralPub
	}
	return nil
}

func (x *Envelope) GetRatchetEnvelope() []byte {
	if x != nil {
		return x.RatchetEnvelope
	}
	return nil
}

func (x *Envelope) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *Envelope) GetWrappedKeys() []*WrappedKey {
	if x != nil {
		return x.WrappedKeys
	}
	return nil
}

type Metadata struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MessageId       uint64                 `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	ChatId          string                 `protobuf:"bytes,2,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`                   // UUID
	SenderId        string                 `protobuf:"bytes,3,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`             // UUID (пользователь или ВП)
	SenderDevice    string                 `protobuf:"bytes,4,opt,name=sender_device,json=senderDevice,proto3" json:"sender_device,omitempty"` // UUID устройства; для ВП — vu_id
	Kind            ContentKind            `protobuf:"varint,5,opt,name=kind,proto3,enum=tima.crypto.v1.ContentKind" json:"kind,omitempty"`
	CreatedAtUnixMs int64                  `protobuf:"varint,6,opt,name=created_at_unix_ms,json=createdAtUnixMs,proto3" json:"created_at_unix_ms,omitempty"`
	ReplyTo         uint64                 `protobuf:"varint,7,opt,name=reply_to,json=replyTo,proto3" json:"reply_to,omitempty"` // 0 = нет ответа
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_envelope_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_envelope_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_envelope_proto_rawDescGZIP(), []int{1}
}

func (x *Metadata) GetMessageId() uint64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *Metadata) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *Metadata) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *Metadata) GetSenderDevice() string {
	if x != nil {
		return x.SenderDevice
	}
	return ""
}

func (x *Metadata) GetKind() ContentKind {
	if x != nil {
		return x.Kind
	}
	return ContentKind_CK_UNSPECIFIED
}

func (x *Metadata) GetCreatedAtUnixMs() int64 {
	if x != nil {
		return x.CreatedAtUnixMs
	}
	return 0
}

func (x *Metadata) GetReplyTo() uint64 {
	if x != nil {
		return x.ReplyTo
	}
	return 0
}

// escrow_blob = mlkem_ct(1088) ‖ SecretBox(message_key, hkdf(mlkem_shared)).
// MLKEM.encapsulate(escrow_pub) → Pair(shared, ct); shared идёт в HKDF, ct — в mlkem_ct.
type EscrowBlob struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	MlkemCt           []byte                 `protobuf:"bytes,1,opt,name=mlkem_ct,json=mlkemCt,proto3" json:"mlkem_ct,omitempty"`                                 // ML-KEM-768 ciphertext, ровно 1088 байт
	WrappedMessageKey []byte                 `protobuf:"bytes,2,opt,name=wrapped_message_key,json=wrappedMessageKey,proto3" json:"wrapped_message_key,omitempty"` // Kodium.encryptSymmetric(hkdf(shared), message_key) → nonce||box
	EscrowKeyVersion  uint32                 `protobuf:"varint,3,opt,name=escrow_key_version,json=escrowKeyVersion,proto3" json:"escrow_key_version,omitempty"`   // версия публичного escrow-ключа
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *EscrowBlob) Reset() {
	*x = EscrowBlob{}
	mi := &file_envelope_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EscrowBlob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EscrowBlob) ProtoMessage() {}

func (x *EscrowBlob) ProtoReflect() protoreflect.Message {
	mi := &file_envelope_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EscrowBlob.ProtoReflect.Descriptor instead.
func (*EscrowBlob) Descriptor() ([]byte, []int) {
	return file_envelope_proto_rawDescGZIP(), []int{2}
}

func (x *EscrowBlob) GetMlkemCt() []byte {
	if x != nil {
		return x.MlkemCt
	}
	return nil
}

func (x *EscrowBlob) GetWrappedMessageKey() []byte {
	if x != nil {
		return x.WrappedMessageKey
	}
	return nil
}

func (x *EscrowBlob) GetEscrowKeyVersion() uint32 {
	if x != nil {
		return x.EscrowKeyVersion
	}
	return 0
}

type WrappedKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Recipient     string                 `protobuf:"bytes,1,opt,name=recipient,proto3" json:"recipient,omitempty"` // device_id (UUID) или vu_id
	Wrapped       []byte                 `protobuf:"bytes,2,opt,name=wrapped,proto3" json:"wrapped,omitempty"`     // Kodium.encrypt(sender_ephemeral_priv, recipient_pub, message_key) → nonce||box
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WrappedKey) Reset() {
	*x = WrappedKey{}
	mi := &file_envelope_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WrappedKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WrappedKey) ProtoMessage() {}

func (x *WrappedKey) ProtoReflect() protoreflect.Message {
	mi := &file_envelope_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WrappedKey.ProtoReflect.Descriptor instead.
func (*WrappedKey) Descriptor() ([]byte, []int) {
	return file_envelope_proto_rawDescGZIP(), []int{3}
}

func (x *WrappedKey) GetRecipient() string {
	if x != nil {
		return x.Recipient
	}
	return ""
}

func (x *WrappedKey) GetWrapped() []byte {
	if x != nil {
		return x.Wrapped
	}
	return nil
}

var File_envelope_proto protoreflect.FileDescriptor

const file_envelope_proto_rawDesc = "" +
	"\n" +
	"\x0eenvelope.proto\x12\x0etima.crypto.v1\"\xfa\x02\n" +
	"\bEnvelope\x12%\n" +
	"\x0eformat_version\x18\x01 \x01(\rR\rformatVersion\x12,\n" +
	"\x04meta\x18\x02 \x01(\v2\x18.tima.crypto.v1.MetadataR\x04meta\x12+\n" +
	"\x11encrypted_payload\x18\x03 \x01(\fR\x10encryptedPayload\x122\n" +
	"\x06escrow\x18\x04 \x01(\v2\x1a.tima.crypto.v1.EscrowBlobR\x06escrow\x120\n" +
	"\x14sender_ephemeral_pub\x18\x05 \x01(\fR\x12senderEphemeralPub\x12)\n" +
	"\x10ratchet_envelope\x18\x06 \x01(\fR\x0fratchetEnvelope\x12\x1c\n" +
	"\tsignature\x18\a \x01(\fR\tsignature\x12=\n" +
	"\fwrapped_keys\x18\b \x03(\v2\x1a.tima.crypto.v1.WrappedKeyR\vwrappedKeys\"\xfd\x01\n" +
	"\bMetadata\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\x04R\tmessageId\x12\x17\n" +
	"\achat_id\x18\x02 \x01(\tR\x06chatId\x12\x1b\n" +
	"\tsender_id\x18\x03 \x01(\tR\bsenderId\x12#\n" +
	"\rsender_device\x18\x04 \x01(\tR\fsenderDevice\x12/\n" +
	"\x04kind\x18\x05 \x01(\x0e2\x1b.tima.crypto.v1.ContentKindR\x04kind\x12+\n" +
	"\x12created_at_unix_ms\x18\x06 \x01(\x03R\x0fcreatedAtUnixMs\x12\x19\n" +
	"\breply_to\x18\a \x01(\x04R\areplyTo\"\x85\x01\n" +
	"\n" +
	"EscrowBlob\x12\x19\n" +
	"\bmlkem_ct\x18\x01 \x01(\fR\amlkemCt\x12.\n" +
	"\x13wrapped_message_key\x18\x02 \x01(\fR\x11wrappedMessageKey\x12,\n" +
	"\x12escrow_key_version\x18\x03 \x01(\rR\x10escrowKeyVersion\"D\n" +
	"\n" +
	"WrappedKey\x12\x1c\n" +
	"\trecipient\x18\x01 \x01(\tR\trecipient\x12\x18\n" +
	"\awrapped\x18\x02 \x01(\fR\awrapped*t\n" +
	"\vContentKind\x12\x12\n" +
	"\x0eCK_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aCK_TEXT\x10\x01\x12\f\n" +
	"\bCK_VOICE\x10\x02\x12\f\n" +
	"\bCK_IMAGE\x10\x03\x12\f\n" +
	"\bCK_VIDEO\x10\x04\x12\v\n" +
	"\aCK_FILE\x10\x05\x12\r\n" +
	"\tCK_SYSTEM\x10\x06B\x99\x01\n" +
	"\x12com.tima.crypto.v1B\rEnvelopeProtoP\x01Z\x1atima/server/internal/proto\xa2\x02\x03TCX\xaa\x02\x0eTima.Crypto.V1\xca\x02\x0eTima\\Crypto\\V1\xe2\x02\x1aTima\\Crypto\\V1\\GPBMetadata\xea\x02\x10Tima::Crypto::V1b\x06proto3"

var (
	file_envelope_proto_rawDescOnce sync.Once
	file_envelope_proto_rawDescData []byte
)

func file_envelope_proto_rawDescGZIP() []byte {
	file_envelope_proto_rawDescOnce.Do(func() {
		file_envelope_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_envelope_proto_rawDesc), len(file_envelope_proto_rawDesc)))
	})
	return file_envelope_proto_rawDescData
}

var file_envelope_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_envelope_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_envelope_proto_goTypes = []any{
	(ContentKind)(0),   // 0: tima.crypto.v1.ContentKind
	(*Envelope)(nil),   // 1: tima.crypto.v1.Envelope
	(*Metadata)(nil),   // 2: tima.crypto.v1.Metadata
	(*EscrowBlob)(nil), // 3: tima.crypto.v1.EscrowBlob
	(*WrappedKey)(nil), // 4: tima.crypto.v1.WrappedKey
}
var file_envelope_proto_depIdxs = []int32{
	2, // 0: tima.crypto.v1.Envelope.meta:type_name -> tima.crypto.v1.Metadata
	3, // 1: tima.crypto.v1.Envelope.escrow:type_name -> tima.crypto.v1.EscrowBlob
	4, // 2: tima.crypto.v1.Envelope.wrapped_keys:type_name -> tima.crypto.v1.WrappedKey
	0, // 3: tima.crypto.v1.Metadata.kind:type_name -> tima.crypto.v1.ContentKind
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_envelope_proto_init() }
func file_envelope_proto_init() {
	if File_envelope_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_envelope_proto_rawDesc), len(file_envelope_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_envelope_proto_goTypes,
		DependencyIndexes: file_envelope_proto_depIdxs,
		EnumInfos:         file_envelope_proto_enumTypes,
		MessageInfos:      file_envelope_proto_msgTypes,
	}.Build()
	File_envelope_proto = out.File
	file_envelope_proto_goTypes = nil
	file_envelope_proto_depIdxs = nil
}
