// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: message_body.proto

// Открытый текст сообщения ДО сжатия и шифрования:
//   MessageBody --serialize--> protobuf --zstd--> Kodium.encryptSymmetric(message_key) = Envelope.encrypted_payload
// Формат текста — plain text + entities (module-boundaries.md §5). Тот же словарь
// EntityType используют посты (publications) — единый рендер.

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EntityType int32

const (
	EntityType_ET_UNSPECIFIED   EntityType = 0
	EntityType_ET_BOLD          EntityType = 1
	EntityType_ET_ITALIC        EntityType = 2
	EntityType_ET_UNDERLINE     EntityType = 3
	EntityType_ET_STRIKETHROUGH EntityType = 4
	EntityType_ET_CODE          EntityType = 5
	EntityType_ET_QUOTE         EntityType = 6
	EntityType_ET_HEADING       EntityType = 7
	EntityType_ET_LIST_ITEM     EntityType = 8
	EntityType_ET_LINK          EntityType = 9
	EntityType_ET_MENTION       EntityType = 10
	EntityType_ET_HASHTAG       EntityType = 11
	EntityType_ET_MEDIA         EntityType = 12
)

// Enum value maps for EntityType.
var (
	EntityType_name = map[int32]string{
		0:  "ET_UNSPECIFIED",
		1:  "ET_BOLD",
		2:  "ET_ITALIC",
		3:  "ET_UNDERLINE",
		4:  "ET_STRIKETHROUGH",
		5:  "ET_CODE",
		6:  "ET_QUOTE",
		7:  "ET_HEADING",
		8:  "ET_LIST_ITEM",
		9:  "ET_LINK",
		10: "ET_MENTION",
		11: "ET_HASHTAG",
		12: "ET_MEDIA",
	}
	EntityType_value = map[string]int32{
		"ET_UNSPECIFIED":   0,
		"ET_BOLD":          1,
		"ET_ITALIC":        2,
		"ET_UNDERLINE":     3,
		"ET_STRIKETHROUGH": 4,
		"ET_CODE":          5,
		"ET_QUOTE":         6,
		"ET_HEADING":       7,
		"ET_LIST_ITEM":     8,
		"ET_LINK":          9,
		"ET_MENTION":       10,
		"ET_HASHTAG":       11,
		"ET_MEDIA":         12,
	}
)

func (x EntityType) Enum() *EntityType {
	p := new(EntityType)
	*p = x
	return p
}

func (x EntityType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EntityType) Descriptor() protoreflect.EnumDescriptor {
	return file_message_body_proto_enumTypes[0].Descriptor()
}

func (EntityType) Type() protoreflect.EnumType {
	return &file_message_body_proto_enumTypes[0]
}

func (x EntityType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EntityType.Descriptor instead.
func (EntityType) EnumDescriptor() ([]byte, []int) {
	return file_message_body_proto_rawDescGZIP(), []int{0}
}

type MessageBody struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`         // UTF-8
	Entities      []*Entity              `protobuf:"bytes,2,rep,name=entities,proto3" json:"entities,omitempty"` // offset/length — в UTF-16 code units (см. README: фикс interop)
	Media         []*MediaRef            `protobuf:"bytes,3,rep,name=media,proto3" json:"media,omitempty"`       // вложения (media_key внутри — под шифрованием body)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageBody) Reset() {
	*x = MessageBody{}
	mi := &file_message_body_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageBody) ProtoMessage() {}

func (x *MessageBody) ProtoReflect() protoreflect.Message {
	mi := &file_message_body_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageBody.ProtoReflect.Descriptor instead.
func (*MessageBody) Descriptor() ([]byte, []int) {
	return file_message_body_proto_rawDescGZIP(), []int{0}
}

func (x *MessageBody) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *MessageBody) GetEntities() []*Entity {
	if x != nil {
		return x.Entities
	}
	return nil
}

func (x *MessageBody) GetMedia() []*MediaRef {
	if x != nil {
		return x.Media
	}
	return nil
}

type Entity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          EntityType             `protobuf:"varint,1,opt,name=type,proto3,enum=tima.crypto.v1.EntityType" json:"type,omitempty"`
	Offset        uint32                 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`                 // начало в UTF-16 code units
	Length        uint32                 `protobuf:"varint,3,opt,name=length,proto3" json:"length,omitempty"`                 // длина в UTF-16 code units
	Url           string                 `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`                        // ET_LINK
	UserId        string                 `protobuf:"bytes,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`    // ET_MENTION
	Attribute     string                 `protobuf:"bytes,6,opt,name=attribute,proto3" json:"attribute,omitempty"`            // ET_HASHTAG — нормализованное имя атрибута (feed-ranking §3)
	MediaId       string                 `protobuf:"bytes,7,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"` // ET_MEDIA (inline в статьях)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entity) Reset() {
	*x = Entity{}
	mi := &file_message_body_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entity) ProtoMessage() {}

func (x *Entity) ProtoReflect() protoreflect.Message {
	mi := &file_message_body_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entity.ProtoReflect.Descriptor instead.
func (*Entity) Descriptor() ([]byte, []int) {
	return file_message_body_proto_rawDescGZIP(), []int{1}
}

func (x *Entity) GetType() EntityType {
	if x != nil {
		return x.Type
	}
	return EntityType_ET_UNSPECIFIED
}

func (x *Entity) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *Entity) GetLength() uint32 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *Entity) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Entity) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Entity) GetAttribute() string {
	if x != nil {
		return x.Attribute
	}
	return ""
}

func (x *Entity) GetMediaId() string {
	if x != nil {
		return x.MediaId
	}
	return ""
}

type MediaRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaId       string                 `protobuf:"bytes,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	MediaKey      []byte                 `protobuf:"bytes,2,opt,name=media_key,json=mediaKey,proto3" json:"media_key,omitempty"` // 32 B — ключ шифрования медиа-объекта (media-storage.md §5)
	Mime          string                 `protobuf:"bytes,3,opt,name=mime,proto3" json:"mime,omitempty"`
	SizeBytes     uint64                 `protobuf:"varint,4,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	Width         uint32                 `protobuf:"varint,5,opt,name=width,proto3" json:"width,omitempty"`
	Height        uint32                 `protobuf:"varint,6,opt,name=height,proto3" json:"height,omitempty"`
	DurationMs    uint32                 `protobuf:"varint,7,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	Blurhash      string                 `protobuf:"bytes,8,opt,name=blurhash,proto3" json:"blurhash,omitempty"`                        // плейсхолдер до загрузки
	ChunkCount    uint32                 `protobuf:"varint,9,opt,name=chunk_count,json=chunkCount,proto3" json:"chunk_count,omitempty"` // >1 → chunked (§10.3)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaRef) Reset() {
	*x = MediaRef{}
	mi := &file_message_body_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaRef) ProtoMessage() {}

func (x *MediaRef) ProtoReflect() protoreflect.Message {
	mi := &file_message_body_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaRef.ProtoReflect.Descriptor instead.
func (*MediaRef) Descriptor() ([]byte, []int) {
	return file_message_body_proto_rawDescGZIP(), []int{2}
}

func (x *MediaRef) GetMediaId() string {
	if x != nil {
		return x.MediaId
	}
	return ""
}

func (x *MediaRef) GetMediaKey() []byte {
	if x != nil {
		return x.MediaKey
	}
	return nil
}

func (x *MediaRef) GetMime() string {
	if x != nil {
		return x.Mime
	}
	return ""
}

func (x *MediaRef) GetSizeBytes() uint64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *MediaRef) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *MediaRef) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *MediaRef) GetDurationMs() uint32 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *MediaRef) GetBlurhash() string {
	if x != nil {
		return x.Blurhash
	}
	return ""
}

func (x *MediaRef) GetChunkCount() uint32 {
	if x != nil {
		return x.ChunkCount
	}
	return 0
}

var File_message_body_proto protoreflect.FileDescriptor

const file_message_body_proto_rawDesc = "" +
	"\n" +
	"\x12message_body.proto\x12\x0etima.crypto.v1\"\x85\x01\n" +
	"\vMessageBody\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x122\n" +
	"\bentities\x18\x02 \x03(\v2\x16.tima.crypto.v1.EntityR\bentities\x12.\n" +
	"\x05media\x18\x03 \x03(\v2\x18.tima.crypto.v1.MediaRefR\x05media\"\xcc\x01\n" +
	"\x06Entity\x12.\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1a.tima.crypto.v1.EntityTypeR\x04type\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\rR\x06offset\x12\x16\n" +
	"\x06length\x18\x03 \x01(\rR\x06length\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\x12\x17\n" +
	"\auser_id\x18\x05 \x01(\tR\x06userId\x12\x1c\n" +
	"\tattribute\x18\x06 \x01(\tR\tattribute\x12\x19\n" +
	"\bmedia_id\x18\a \x01(\tR\amediaId\"\x81\x02\n" +
	"\bMediaRef\x12\x19\n" +
	"\bmedia_id\x18\x01 \x01(\tR\amediaId\x12\x1b\n" +
	"\tmedia_key\x18\x02 \x01(\fR\bmediaKey\x12\x12\n" +
	"\x04mime\x18\x03 \x01(\tR\x04mime\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x04 \x01(\x04R\tsizeBytes\x12\x14\n" +
	"\x05width\x18\x05 \x01(\rR\x05width\x12\x16\n" +
	"\x06height\x18\x06 \x01(\rR\x06height\x12\x1f\n" +
	"\vduration_ms\x18\a \x01(\rR\n" +
	"durationMs\x12\x1a\n" +
	"\bblurhash\x18\b \x01(\tR\bblurhash\x12\x1f\n" +
	"\vchunk_count\x18\t \x01(\rR\n" +
	"chunkCount*\xdc\x01\n" +
	"\n" +
	"EntityType\x12\x12\n" +
	"\x0eET_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aET_BOLD\x10\x01\x12\r\n" +
	"\tET_ITALIC\x10\x02\x12\x10\n" +
	"\fET_UNDERLINE\x10\x03\x12\x14\n" +
	"\x10ET_STRIKETHROUGH\x10\x04\x12\v\n" +
	"\aET_CODE\x10\x05\x12\f\n" +
	"\bET_QUOTE\x10\x06\x12\x0e\n" +
	"\n" +
	"ET_HEADING\x10\a\x12\x10\n" +
	"\fET_LIST_ITEM\x10\b\x12\v\n" +
	"\aET_LINK\x10\t\x12\x0e\n" +
	"\n" +
	"ET_MENTION\x10\n" +
	"\x12\x0e\n" +
	"\n" +
	"ET_HASHTAG\x10\v\x12\f\n" +
	"\bET_MEDIA\x10\fB\x9c\x01\n" +
	"\x12com.tima.crypto.v1B\x10MessageBodyProtoP\x01Z\x1atima/server/internal/proto\xa2\x02\x03TCX\xaa\x02\x0eTima.Crypto.V1\xca\x02\x0eTima\\Crypto\\V1\xe2\x02\x1aTima\\Crypto\\V1\\GPBMetadata\xea\x02\x10Tima::Crypto::V1b\x06proto3"

var (
	file_message_body_proto_rawDescOnce sync.Once
	file_message_body_proto_rawDescData []byte
)

func file_message_body_proto_rawDescGZIP() []byte {
	file_message_body_proto_rawDescOnce.Do(func() {
		file_message_body_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_message_body_proto_rawDesc), len(file_message_body_proto_rawDesc)))
	})
	return file_message_body_proto_rawDescData
}

var file_message_body_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_message_body_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_message_body_proto_goTypes = []any{
	(EntityType)(0),     // 0: tima.crypto.v1.EntityType
	(*MessageBody)(nil), // 1: tima.crypto.v1.MessageBody
	(*Entity)(nil),      // 2: tima.crypto.v1.Entity
	(*MediaRef)(nil),    // 3: tima.crypto.v1.MediaRef
}
var file_message_body_proto_depIdxs = []int32{
	2, // 0: tima.crypto.v1.MessageBody.entities:type_name -> tima.crypto.v1.Entity
	3, // 1: tima.crypto.v1.MessageBody.media:type_name -> tima.crypto.v1.MediaRef
	0, // 2: tima.crypto.v1.Entity.type:type_name -> tima.crypto.v1.EntityType
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_message_body_proto_init() }
func file_message_body_proto_init() {
	if File_message_body_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_message_body_proto_rawDesc), len(file_message_body_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_body_proto_goTypes,
		DependencyIndexes: file_message_body_proto_depIdxs,
		EnumInfos:         file_message_body_proto_enumTypes,
		MessageInfos:      file_message_body_proto_msgTypes,
	}.Build()
	File_message_body_proto = out.File
	file_message_body_proto_goTypes = nil
	file_message_body_proto_depIdxs = nil
}
